version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: Eya378
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./SpringSecEx
    container_name: springboot-container
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: Eya378

      SPRING_MAIL_PASSWORD: zulviaredqcefadg
      SPRING_MAIL_USERNAME: ayaskhiri925@gmail.com
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  frontend:
    build: ./FrontStage
    container_name: angular-container
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
